### ISSUE TITLE
issue when using speechbrain as submodule. 

### ISSUE THREAD

**Issue by vmcru** [speechbrain/benchmarks#20]
when running `git submodule init` during install, get this error: `fatal: not a git repository (or any of the parent directories): .git`

instead of doing this immediately after cloning, do `cd benchmarks` then the command. It also fails the pytest tests

**Comment by Adel-Moumen** [comment]
Hello @vmcru, thanks for letting us know. We are still working on this benchmarks and we will resolve all the issues very soon. :-) 

Best.

**Comment by mravanelli** [comment]
I updated the documentation with the fixed commands to run. @vmcru, please double check

**Comment by vmcru** [comment]
The installation works flawlessly now. I ran the pytests and got some errors but other than that it seems to work now.
